spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_catalogo
    username: postgres
    password: kdanilo1102
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true